# Generated by Django 5.1.3 on 2024-11-07 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('growth_stage', models.CharField(max_length=100)),
                ('health_status', models.CharField(max_length=100)),
                ('sensor_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.sensordata')),
            ],
        ),
    ]
