# Generated by Django 5.1.3 on 2024-11-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('optimal_ph', models.FloatField()),
                ('optimal_temp', models.FloatField()),
                ('nutrient_requirement', models.CharField(max_length=100)),
            ],
        ),
    ]
